from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

import torch
from dotenv import load_dotenv
from huggingface_hub import login
from transformers import pipeline


MODEL_NAME = "google/gemma-3-1b-it"
DEVICE = -1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Clean a Faster-Whisper JSON transcript with Gemma on CPU."
    )
    parser.add_argument(
        "json_file",
        type=Path,
        help="Path to a JSON transcript generated by run.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output"),
        help="Directory for TXT output. Defaults to output/.",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=2048,
        help="Maximum number of tokens Gemma may generate per chunk.",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=12000,
        help="Maximum transcript characters to send to Gemma at once.",
    )
    return parser.parse_args()


def login_to_hugging_face_if_available() -> bool:
    load_dotenv()
    token = os.getenv("HF_TOKEN")
    if not token:
        return False

    login(token=token)
    return True


def load_transcript(json_file: Path) -> dict[str, Any]:
    with json_file.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError("Transcript JSON must be an object.")
    return data


def extract_text(transcript: dict[str, Any]) -> str:
    text = transcript.get("text")
    if isinstance(text, str) and text.strip():
        return text.strip()

    segments = transcript.get("segments", [])
    if isinstance(segments, list):
        segment_texts = [
            segment.get("text", "").strip()
            for segment in segments
            if isinstance(segment, dict)
        ]
        return "\n".join(text for text in segment_texts if text)

    return ""


def build_prompt(transcript_text: str) -> str:
    return f"""以下は音声文字起こしの結果です。
内容を変えずに、読みやすい日本語の文章へ整形してください。

要件:
- 明らかな誤記や誤変換だけを自然に修正する
- 「えー」「あのー」「そのー」など意味を持たないフィラーやノイズを削除する
- 話題のまとまりごとに適切に改行する
- 事実、数値、固有名詞を推測で追加しない
- 出力は整形後の本文のみ

文字起こし:
{transcript_text}
"""


def chunk_text(text: str, chunk_size: int) -> list[str]:
    if chunk_size <= 0:
        raise ValueError("chunk_size must be greater than 0.")

    chunks: list[str] = []
    current = ""
    for paragraph in text.splitlines():
        paragraph = paragraph.strip()
        if not paragraph:
            continue
        if len(paragraph) > chunk_size:
            if current:
                chunks.append(current)
                current = ""
            chunks.extend(
                paragraph[start : start + chunk_size]
                for start in range(0, len(paragraph), chunk_size)
            )
            continue
        if len(current) + len(paragraph) + 1 > chunk_size:
            chunks.append(current)
            current = paragraph
        else:
            current = f"{current}\n{paragraph}".strip()

    if current:
        chunks.append(current)
    return chunks


def build_generator() -> Any:
    return pipeline(
        "text-generation",
        model=MODEL_NAME,
        device=DEVICE,
        dtype=torch.float32,
    )


def clean_chunk(generator: Any, transcript_text: str, max_new_tokens: int) -> str:
    messages = [
        {
            "role": "user",
            "content": build_prompt(transcript_text),
        }
    ]
    result = generator(
        messages,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        clean_up_tokenization_spaces=False,
        return_full_text=False,
    )
    generated = result[0]["generated_text"]
    if isinstance(generated, list):
        return generated[-1].get("content", "").strip()
    return str(generated).strip()


def clean_text(transcript_text: str, max_new_tokens: int, chunk_size: int) -> str:
    generator = build_generator()
    cleaned_chunks = [
        clean_chunk(generator, chunk, max_new_tokens)
        for chunk in chunk_text(transcript_text, chunk_size)
    ]
    return "\n\n".join(chunk for chunk in cleaned_chunks if chunk)


def source_stem(transcript: dict[str, Any], json_file: Path) -> str:
    source = transcript.get("source")
    if isinstance(source, dict):
        file_name = source.get("file_name")
        if isinstance(file_name, str) and file_name.strip():
            return Path(file_name).stem
    return json_file.stem


def build_output_path(
    transcript: dict[str, Any],
    json_file: Path,
    output_dir: Path,
) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    model_slug = MODEL_NAME.replace("/", "_")
    return output_dir / f"{source_stem(transcript, json_file)}_{model_slug}_{timestamp}.txt"


def main() -> None:
    args = parse_args()
    json_file = args.json_file.expanduser().resolve()
    output_dir = args.output_dir.expanduser().resolve()

    if not json_file.is_file():
        raise FileNotFoundError(f"JSON file not found: {json_file}")

    logged_in = login_to_hugging_face_if_available()
    transcript = load_transcript(json_file)
    transcript_text = extract_text(transcript)
    if not transcript_text:
        raise ValueError("Transcript text is empty.")

    cleaned_text = clean_text(transcript_text, args.max_new_tokens, args.chunk_size)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = build_output_path(transcript, json_file, output_dir)
    output_path.write_text(cleaned_text + "\n", encoding="utf-8")

    print(output_path)
    print(f"Hugging Face login: {logged_in}")


if __name__ == "__main__":
    main()
